### ISSUE TITLE
HomeKit Tv Service Support

### ISSUE THREAD

**Issue by donavanbecker** [rwifall/homebridge-sonybraviatv#17]
Now that HomeBridge has been updated to support tv services, can this be added to this Plugin?

**Comment by russellh76** [comment]
I've been wondering if we should try and combine the 5 or 6 Bravia modules out there into a full featured platform.  I've got a larger feature set in mine, but they're all individual switches.  https://github.com/russellh76/homebridge-sonybraviaswitchestv

Can you expand on what you mean by TV services?  Got a link or something?

**Comment by donavanbecker** [comment]
Would you be able to do this?

https://twitter.com/KhaosT/status/1088680375398744064

https://twitter.com/KhaosT/status/1088678984970162176

**Comment by rwifall** [comment]
Unfortunately, I don't use homebridge anymore as I have migrated to HomeAssistant.
So I won't be able to update this plugin to support TV services, or to combine it with other modules.

**Comment by lswee** [comment]
I think if this possible, there only need be one plugin.

Could you do this russellh76?

I can give you iOS beta access.

**Comment by russellh76** [comment]
I'm hesitant to take ownership of such an effort.  Happy to contribute.  For the most part this coding isn't that difficult. The real issue is examples, which for the Sony Bravia portion I can easily provide.  How platforms or new TV capability in Homekit works are unknown to me.  Why don't you guys fire up a project.  Invite me (and all the other Bravia TV homebridge folks).  Try and find an example of the new TV code if you can.  The TV functionality is new, so documentation and examples are probably scarce.

**Comment by arnif** [comment]
Here it is: https://github.com/arnif/homebridge-sony-television
